version: "3.2"
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile-node
    image: rptools/maptool-server-listing
    env_file:
      - .env
    ports:
      - "5000:3000"
    container_name: maptool-server-listing
    restart: unless-stopped
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile-db
    image: rptools/maptool-server-listing-db
    env_file:
      - .env
    volumes:
      - maptool-server-listing-db-vol:/var/lib/mysql
    container_name: maptool-server-listing-db
    restart: unless-stopped


volumes:
  maptool-server-listing-db-vol:
